version: "3"

services:
  app:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/fastapi-admin
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8001:8000" # 左边是宿主机的
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi-admin
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always
    volumes:
      - ./data/redis_data:/data

volumes:
  mysql_data:
  redis_data:
